server:
  port: 8080
spring:
  datasource:
    username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

mybatis:
  mapper-location: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.domain


